from ..template import Template

names_eng = Template(
    names=[
        'Bond of Life',
        'Life Bond',
        'Hexerei: Secret Rite effects',
        'Hexerei',

        'Nightsoul\'s Blessing',
        'Nightsoul point',
        'Nightsoul points',
        'Nightsoul Burst',
        'Nightsoul Bursts',

        'Moonsign',
        'Moondrifts',
        'Nascent Gleam',
        'Ascendant Gleam',
        'Lunar Reactions',
        'Lunar Reaction DMG',
        'Elemental DMG Bonus',
        'Charged Attack DMG',
        'Elemental Burst DMG',
        'Elemental Skill DMG',
        'Elemental reaction',
        'Normal Attack DMG',
        'Normal Attack SPD',
        'Plunging Attack DMG',
        'Reaction DMG',
        'Elemental DMG',

        'Elemental Shard',
        'Elemental Skill',
        'Elemental Burst',
        'Elemental Bursts',
        'Bursts',
        'Burst',
        'Elemental Reaction',
        'Elemental Skills',
        'Normal Attack',
        'Normal Attacks',
        'Charged Attack',
        'Charged Attacks',
        'Charge Attacks',
        'Plunging Attack',
        'Plunging Attacks',
        'Stamina cost',

        'Incoming Healing Bonus',
        'Healing Bonus',
        'Physical DMG Bonus',
        'Physical DMG',
        'Elemental RES',
        'Physical RES',
        'DMG Bonus',
        'Movement SPD',
        'Attack SPD',
        'ATK SPD',
        'AoE DMG',

        'Vaporize',
        'Melt',

        'Sword',
        'Claymore',
        'Polearm',
        'Catalyst',
        'Bow',
        'Normal',
        'Charged',

        'Elemental Mastery',
        'Shield Strength',
        'Energy Recharge',
        'Healing Effectiveness',
        'Healing Bonus',
        'Max HP',
        'CRIT Rate',
        'CRIT DMG',
        'Crit DMG',
        'CRIT Hit',
        'HP',
        'Base ATK',
        'ATK DMG',
        'ATK',
        'DEF',
        'Elemental Energy',
        'Energy',
        'Elemental Orb',
        'Elemental Particle',
        'Orb',
        'Particle',
    ],
)

keywords_eng = Template(
    keywords=[
        ('Lunar-Bloom DMG', 'dendro'),
        ('Lunar-Bloom', 'dendro'),
        ('Lunar-Crystallize', 'geo'),
        ('Moondrift Harmony', 'geo'),

        ('Anemo DMG Bonus', 'anemo'),
        ('Cryo DMG Bonus', 'cryo'),
        ('Electro DMG Bonus', 'electro'),
        ('Geo DMG Bonus', 'geo'),
        ('Hydro DMG Bonus', 'hydro'),
        ('Pyro DMG Bonus', 'pyro'),
        ('Dendro DMG Bonus', 'dendro'),

        ('Anemo DMG', 'anemo'),
        ('Cryo DMG', 'cryo'),
        ('Electro DMG', 'electro'),
        ('Geo DMG', 'geo'),
        ('Hydro DMG', 'hydro'),
        ('Pyro DMG', 'pyro'),
        ('Dendro DMG', 'dendro'),

        ('Anemo RES', 'anemo'),
        ('Cryo RES', 'cryo'),
        ('Electro RES', 'electro'),
        ('Geo RES', 'geo'),
        ('Hydro RES', 'hydro'),
        ('Pyro RES', 'pyro'),
        ('Dendro RES', 'dendro'),

        ('Electro-Charged', 'electro'),
        ('Lunar-Charged', 'electro'),
        ('Crystallize Reaction', 'geo'),
        ('Electro Crystallize', 'electro'),
        ('Hydro Crystallize', 'hydro'),
        ('Cryo Crystallize', 'cryo'),
        ('Pyro Crystallize', 'pyro'),
        ('Crystallize', 'geo'),
        ('Frozen', 'cryo'),
        ('Overloaded', 'pyro'),
        ('Burning', 'pyro'),
        ('Superconduct', 'cryo'),
        ('Electro-infused Swirl', 'electro'),
        ('Electro Swirl', 'electro'),
        ('Hydro Swirl', 'hydro'),
        ('Hydro-infused Swirl', 'hydro'),
        ('Cryo Swirl', 'cryo'),
        ('Pyro Swirl', 'pyro'),
        ('Swirl', 'anemo'),
        ('Quicken', 'dendro'),
        ('Burgeon', 'dendro'),
        ('Hyperbloom', 'dendro'),
        ('Bloom', 'dendro'),
        ('Aggravate', 'electro'),
        ('Spread', 'dendro'),

        ('Dendro Cores', 'dendro'),
        ('Dendro Core', 'dendro'),

        ('Anemo', 'anemo'),
        ('Cryo', 'cryo'),
        ('Electro', 'electro'),
        ('Geo', 'geo'),
        ('Hydro', 'hydro'),
        ('Pyro', 'pyro'),
        ('Dendro', 'dendro'),
    ]
)

patterns_eng = Template(
    patterns=[
        (r'{M#(.*?)}', '\\1'),
        (r'{F#(.*?)}', ''),
        (r'{LAYOUT_PC#(.*?)}', '\\1'),
        (r'{LAYOUT_\w+#.*?}', ''),
        (r'{LINK\#N(\d+)}<color=\#\w+>(.*?)<\/color>{/LINK}', 'skill{n\\1:\\2}'),
        (r'{LINK\#N(\d+)}<color style=\'color\:\#\w+;\'>(.*?)<\/color>{/LINK}', 'skill{n\\1:\\2}'),
        (r'{LINK\#N(\d+)}(.*?){/LINK}', 'skill{n\\1:\\2}'),
        (r'{LINK\#\w+}(.*?){/LINK}', '\\1'),
        (r'<color=\#99FFFFFF>(.*?)<\/color>', 'cryo{\\1}'),
        (r'<color=\#FFE699FF>(.*?)<\/color>', 'geo{\\1}'),
        (r'<color=\#FF9999FF>(.*?)<\/color>', 'pyro{\\1}'),
        (r'<color=\#80C0FFFF>(.*?)<\/color>', 'hydro{\\1}'),
        (r'<color=\#FFACFFFF>(.*?)<\/color>', 'electro{\\1}'),
        (r'<color=\#80FFD7FF>(.*?)<\/color>', 'anemo{\\1}'),
        (r'<color=\#99FF88FF>(.*?)<\/color>', 'dendro{\\1}'),
        # (r'<color=\#FFD780FF>(.*?)<\/color>\\n', '<h2>\\1</h2>\\\\n'),
        (r'<color=\#FFD780FF>(.*?)<\/color>', 'name{\\1}'),

        (r"<color style='color\:\#99FFFF;'>(.*?)<\/color>", 'name{\\1}'),
        (r"<color style='color\:\#FFE699;'>(.*?)<\/color>", 'geo{\\1}'),
        (r"<color style='color\:\#FF9999;'>(.*?)<\/color>", 'pyro{\\1}'),
        (r"<color style='color\:\#80C0FF;'>(.*?)<\/color>", 'hydro{\\1}'),
        (r"<color style='color\:\#FFACFF;'>(.*?)<\/color>", 'electro{\\1}'),
        (r"<color style='color\:\#80FFD7;'>(.*?)<\/color>", 'anemo{\\1}'),
        (r"<color style='color\:\#99FF88;'>(.*?)<\/color>", 'dendro{\\1}'),
        (r"<color style='color\:\#FFD780;'>(.*?)<\/color>", 'name{\\1}'),
        (r'\\n', '<>'),
    ],
)

postprocess = Template(
    patterns=[
        # (r'</h2>(\\n)+', '</h2><p>'),
        (r'^([^<])', '<p>\\1'),
        (r'((<>)+)$', ''),
        (r'<><> ?', '</p><p>'),
        (r'<> ?', '<br>'),
        (r'$', '</p>'),
        (r'<p><h2>', '<h2>'),
        (r'<p>#', '<p>'),
    ]
)

color_patterns = Template(
    patterns=[
        (r'<color=\#99FFFFFF>(.*?)<\/color>', 'name{\\1}'),
        (r'<color=\#FFE699FF>(.*?)<\/color>', 'geo{\\1}'),
        (r'<color=\#FF9999FF>(.*?)<\/color>', 'pyro{\\1}'),
        (r'<color=\#80C0FFFF>(.*?)<\/color>', 'hydro{\\1}'),
        (r'<color=\#FFACFFFF>(.*?)<\/color>', 'electro{\\1}'),
        (r'<color=\#80FFD7FF>(.*?)<\/color>', 'anemo{\\1}'),
        (r'<color=\#99FF88FF>(.*?)<\/color>', 'dendro{\\1}'),
        (r'<color=\#FFD780FF>(.*?)<\/color>', 'name{\\1}'),

        (r"<color style='color\:\#99FFFF;'>(.*?)<\/color>", 'name{\\1}'),
        (r"<color style='color\:\#FFE699;'>(.*?)<\/color>", 'geo{\\1}'),
        (r"<color style='color\:\#FF9999;'>(.*?)<\/color>", 'pyro{\\1}'),
        (r"<color style='color\:\#80C0FF;'>(.*?)<\/color>", 'hydro{\\1}'),
        (r"<color style='color\:\#FFACFF;'>(.*?)<\/color>", 'electro{\\1}'),
        (r"<color style='color\:\#80FFD7;'>(.*?)<\/color>", 'anemo{\\1}'),
        (r"<color style='color\:\#99FF88;'>(.*?)<\/color>", 'dendro{\\1}'),
        (r"<color style='color\:\#FFD780;'>(.*?)<\/color>", 'name{\\1}'),
    ]
)

names_rus = Template(
    names=[
        'Долг жизни',
        'Долгом жизни',
        'Долга жизни',
        'Ведьмовство: Тайный обряд',
        'Ведьмовски[хме]',

        'Вспышку Ночного духа',
        'Вспышке Ночного духа',
        'Благословение Ночного духа',
        'Благословения Ночного духа',
        'Ночного духа',

        'элементальной сферы',
        'частицы',
        'элементальные сферы',
        'частицы',
        'Лунное знамение',
        'Лунная пелена',
        'Зарождающееся сияние',
        'Высшее сияние',
        'Лунные реакции',
        'Лунных реакций',
        '[эЭ]лементальны[йх] навык(ов)?',
        'урона всеми элементами',
        'урон элементального навыка',
        'элементального навыка',
        'элементальные навыки',
        'Элементальным навыком',
        'элементальным навыком',
        'элементальными навыками',
        'взрыв(ом|а|ы)? стихи(и|й)',
        'элементальный осколок',
        'элементальному урону',
        'элементального урона',
        'элементальный урон',
        'элементальной реакции',
        'урон заряженной атаки',
        '[Уу]рон(ом)? обычной атаки',
        'урон по площади',
        'Скорость обычной атаки',
        'скорость обычной атаки',
        '[оО]бычн(ой|ых|ую|ые|ая|ыми) атак(и|ой|е|у|а|ами)?',
        'урон(ом)? обычной',
        'Обычн(ой|ая|ые)',
        '[зЗ]аряженн(ой|ых|ую|ые|ая|ыми) атак(и|ой|е|у|а|ами)?',
        'атаками в падении',
        'атаки в падении',
        'атаку в падении',
        'атака в падении',
        'бонус физического урона',
        'бонус лечения',
        'атакой в падении',
        'атак в падении',

        'единиц энергии',
        'элементальной энергии',
        'элементальная энергия',
        'Пар',
        'Таяние',
        'скорость передвижения',
        'скорость атаки',

        'одноручное',
        'двуручное',
        'древковое',
        'катализатор',
        'стрелковое',

        'шанс критического попадания',
        'Шанс крит. попадания',
        'критический урон',
        'Крит. попадания обычной',
        'крит. урон',
        'крит. урона',
        'Крит. урон',
        'бонус получаемого лечения',

        'восстановления энергии',
        'восстановление энергии',
        '[Мм]астерств[оау] стихи[йи]',
        'шанс крит. попадания',
        'Прочность щита',
        'прочность щита',
        'физ. урон',
        'Сила атаки',
        'сила атаки',
        'силу атаки',
        'силы атаки',
        'силе атаки',
        'Защита',
        'эффективность лечения',
        'Бонус лечения',
        'бонус получаемого лечения',
        'получаемое лечение',
        'Макс. HP',
        'макс. HP',
        'макс. НР',
        'HP',
        'НР',
        'ед. энергии',
    ]
)

keywords_rus = Template(
    keywords=[
        ('Лунная бутонизация', 'dendro'),
        ('Лунную бутонизацию', 'dendro'),
        ('Лунной бутонизации', 'dendro'),
        ('Лунный кристалл', 'geo'),
        ('Гармони[ия] Лунной пелены', 'geo'),

        ('Гео урона', 'geo'),
        ('Гео урону', 'geo'),
        ('Гео урон', 'geo'),
        ('Пиро урона', 'pyro'),
        ('Пиро урон', 'pyro'),
        ('Крио урона', 'cryo'),
        ('Крио урон', 'cryo'),
        ('Электро урона', 'electro'),
        ('Электро урон', 'electro'),
        ('Анемо урона', 'anemo'),
        ('Анемо урон', 'anemo'),
        ('Гидро урона', 'hydro'),
        ('Гидро урон', 'hydro'),
        ('Дендро урона', 'dendro'),
        ('Дендро урон', 'dendro'),

        ('Гидро сопротивление', 'hydro'),
        ('Дендро сопротивление', 'dendro'),
        ('Электро сопротивление', 'electro'),
        ('Крио сопротивление', 'cryo'),
        ('Гео сопротивление', 'geo'),
        ('Анемо сопротивление', 'anemo'),
        ('Пиро сопротивление', 'pyro'),

        ('Дендро ядра', 'dendro'),
        ('Дендро ядер', 'dendro'),

        ('Заряжен', 'electro'),
        ('Лунный заряд', 'electro'),
        ('Электро Кристалл', 'electro'),
        ('Гидро Кристалл', 'hydro'),
        ('Крио Кристалл', 'cryo'),
        ('Пиро Кристалл', 'pyro'),
        ('Кристалл', 'geo'),
        ('Заморозка', 'cryo'),
        ('Перегрузка', 'pyro'),
        ('Горение', 'pyro'),
        ('Горения', 'pyro'),
        ('Сверхпроводник', 'cryo'),
        ('Крио Рассеивание', 'cryo'),
        ('Гидро Рассеивание', 'hydro'),
        ('Гидро рассеивание', 'hydro'),
        ('Пиро Рассеивание', 'pyro'),
        ('Электро Рассеивание', 'electro'),
        ('Рассеивание', 'anemo'),
        ('Рассеиваниe', 'anemo'),
        ('Рассеивания', 'anemo'),
        ('Рассенивание', 'anemo'),
        ('Стимуляцию', 'dendro'),
        ('Стимуляция', 'dendro'),
        ('Бутонизацию', 'dendro'),
        ('Бутонизация', 'dendro'),
        ('Цветение', 'dendro'),
        ('Вегетация', 'dendro'),
        ('Вегетацию', 'dendro'),
        ('Обострение', 'electro'),
        ('Разрастание', 'dendro'),

        ('Гео', 'geo'),
        ('Пиро', 'pyro'),
        ('Крио', 'cryo'),
        ('Электро', 'electro'),
        ('Анемо', 'anemo'),
        ('Гидро', 'hydro'),
        ('Дендро', 'dendro'),

    ]
)
