name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Build
      run: |
        npm install
        npm run build

    - name: Deploy to GitHub Pages
      run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          cp -r dist/* docs
          git add docs
          git commit -m "Deploy $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin gh-pages
    
