from ...template import Template, TemplateList


char_lauma = TemplateList(
    default_rus=Template(
        names=[
            'Лаума',
        ],
        keywords=[
            ('Лунная бутонизация', 'dendro'),
            ('Бутонизация', 'dendro'),
            ('Вегетация', 'dendro'),
            ('Цветение', 'dendro'),
        ],
        skills={
            'skill': ['Рунная песнь: Безрассветный покой карсикко'],
            'burst': ['Рунная песнь: Сердца становятся луной'],
        },
    ),
    default_eng=Template(
        names=[
            'Lauma',
        ],
        keywords=[
            ('Lunar-Bloom DMG', 'dendro'),
            ('Bloom', 'dendro'),
            ('Hyperbloom', 'dendro'),
            ('Burgeon', 'dendro'),
        ],
        skills={
            'skill': ['Runo: Dawnless Rest of Karsikko'],
            'burst': ['Runo: All Hearts Become the Beating Moon'],
        },
    ),
    dawnless_rest_of_karsikko_rus = Template(
        sentences=[
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            ['1:ignore'],
            [],
            [],
            ['3:ignore'],
            [],
            ['10:ignore'],
            [],
            [],
            [],
            [],
            [],
        ],
        results=[
            list(range(0, 20)),
            [14],
        ],
    ),
    dawnless_rest_of_karsikko_eng = Template(
        sentences=[
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            ['1:ignore'],
            [],
            [],
            ['3:ignore'],
            [],
            ['10:ignore'],
            [],
            [],
            [],
            [],
            [],
        ],
        results=[
            list(range(0, 19)),
            [13],
        ],
    ),
    all_hearts_become_the_beating_moon = Template(
        sentences=[
            [],
            ['18:'],
            [],
            ['15:ignore', '6:'],
            ['15:ignore'],
            [],
            [],
            [],
            ['1:'],
            [],
            [],
            [],
            [],
            [],
        ],
        results=[
            list(range(0, 14)),
            [6],
            [8, 9, 10, 11]
        ],
        extracted_names=[1],
    ),
    light_for_the_frosty_night_rus=Template(
        sentences=[
            ['20:ignore'],
            [],
            [],
            [],
            [],
            [],
            ['15:format{text_number_f=1|{value}}:text_crit_rate_bloom', '100:format{text_number_f=1|{value}}:text_crit_dmg_bloom'],
            [],
            [],
            [],
            [],
            ['10:format{text_number_f=2|{value}}:text_crit_rate_lunarbloom', '20:format{text_number_f=2|{value}}:text_crit_dmg_lunarbloom'],
        ],
        results=[
            [0, 1],
            [3],
            [5, 6, 7],
            [9],
            [11],
            list(range(0, 12)),
        ],
        extracted_names=[1, 3],
    ),
    light_for_the_frosty_night_eng=Template(
        sentences=[
            ['20:ignore'],
            [],
            [],
            [],
            [],
            ['15:format{text_number_f=1|{value}}:text_crit_rate_bloom', '100:format{text_number_f=1|{value}}:text_crit_dmg_bloom'],
            [],
            [],
            [],
            [],
            ['10:format{text_number_f=2|{value}}:text_crit_rate_lunarbloom', '20:format{text_number_f=2|{value}}:text_crit_dmg_lunarbloom'],
        ],
        results=[
            [0, 1],
            [3],
            [5, 6],
            [8],
            [10],
            list(range(0, 11)),
        ],
        extracted_names=[1, 3],
    ),
    i_offer_blood_and_tears_to_the_moonlight_rus=Template(
        sentences=[
            ['185:text_percent_skill_dmg'],
            ['2:'],
            [],
            ['8:'],
            [],
            [],
            ['1:ignore', '150:text_percent_atk_dmg'],
            [],
            [],
            ['25:format{text_number_f=2|{value}}:text_percent_lunarbloom_bonus'],
        ],
        results=[
            list(range(0, 10)),
            [9],
        ],
    ),
    i_offer_blood_and_tears_to_the_moonlight_eng=Template(
        sentences=[
            ['1:ignore', '185:text_percent_skill_dmg'],
            [],
            ['2:'],
            [],
            ['8:'],
            [],
            [],
            ['1:ignore', '150:text_percent_atk_dmg'],
            [],
            [],
            ['25:format{text_number_f=2|{value}}:text_percent_lunarbloom_bonus'],
        ],
        results=[
            list(range(0, 11)),
            [10],
        ],
    ),
    twine_warnings_and_tales_from_the_north=Template(
        sentences=[
            [],
            [],
            ['500:text_bloom_percent', '400:text_lunarbloom_percent'],
            [],
            ['40:format{text_number_f=2|{value}}:text_dmg_reaction_lunarbloom'],
        ],
    ),
)
