from ...template import Template, TemplateList


char_raiden_shogun = TemplateList(
    default_rus=Template(
        names=[
            'сёгуна Райдэн', 'сёгун Райдэн',
            'Чакра вожделения', 'Решимости', 'Решимость', 'Мусо иссин',
            'взрывов стихии', 'взрыв стихии', 'Мусо но хитотати',
        ],
        keywords=[('Глаза грозового наказания', 'skill')],
        skills={
            'skill': ['Чакра вожделения', 'Глаза грозового наказания'],
            'burst': ['Мусо иссин', 'Тайное искусство: Мусо синсэцу'],
        },
    ),
    default_eng=Template(
        names=[
            'Chakra Desiderata', 'Resolve', 'Musou Isshin',
            'Musou no Hitotachi', 'Raiden Shogun',
        ],
        keywords=[('Eye of Stormy Judgment', 'skill')],
        skills={
            'skill': ['Chakra Desiderata', 'Eye of Stormy Judgment'],
            'burst': ['Musou Isshin', 'Secret Art: Musou Shinsetsu'],
        },
    ),
    baleful_omen=Template(
        replace={
            '· ': '· \n',
        },
        sentences=[
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            ['0.9:ignore'],
            [],
            ['20:ignore'],
            [],
            [],
            [],
        ],
        results=[
            list(range(0, 16)),
            [8],
            [2],
        ],
        extracted_names=[2],
    ),
    baleful_omen_eng=Template(
        replace={
            '·': '·\n',
        },
        sentences=[
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            ['0.9:ignore'],
            [],
            ['20:ignore'],
            [],
            [],
        ],
        results=[
            list(range(0, 15)),
            [8],
            [2],
        ],
        extracted_names=[2],
    ),
    musou_shinsetsu_rus=Template(
        sentences=[
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            ['1:ignore', '5:ignore'],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            ['60:ignore'],
            [],
            ['300:ignore'],
            [],
            [],
            [],
            [],
        ],
        results=[
            list(range(0, 25)),
            [5, 6, 7, 8, 9, 10],
            [3],
            [1],
        ],
        extracted_names=[2],
    ),
    musou_shinsetsu_eng=Template(
        sentences=[
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            ['1:ignore', '5:ignore'],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            ['60:ignore'],
            [],
            ['300:ignore'],
            [],
            [],
            [],
            [],
        ],
        results=[
            list(range(0, 26)),
            [5, 6, 7, 8, 9],
            [3],
            [1],
        ],
        extracted_names=[2],
    ),
    wishes_unnumbered=Template(
        sentences=[
            ['ignore'],
            [],
            ['ignore'],
          ],
    ),
    enlightened_one=Template(
        sentences=[
            ['ignore', 'ignore'],
            [],
            [None],
            [],
            [None],
        ],
    ),
    ominous_inscription=Template(
        sentences=[
            [],
            ['ignore'],
            ['ignore'],
        ],
    ),
    steelbreaker=Template(
        sentences=[
            ['enemy_def_ignore_burst'],
        ],
    ),
    pledge_of_propriety=Template(
        sentences=[
            ['text_percent', 'ignore'],
        ],
    ),
    wishbearer=Template(
        sentences=[
            ['ignore'],
            [],
            ['ignore', 'ignore'],
        ],
    ),
)
