from ...template import Template, TemplateList


char_wriothesley = TemplateList(
    default_rus=Template(
        names=[
            'Ризли',
            'Кулаков изгнания', 'Кулаки изгнания', 'Благодатное взыскание: Раскрытие', 'Благодатное взыскание', 'Благодатного взыскания',
            'заряженная атака', 'Взыскани(я|ем?): Морозный кулак в прыжке',
            'Леденящего наказания', 'Леденящее наказание', 'Несправедливость будет раскрыта',
            'Сияни(я|ем?): Морозный кулак в прыжке',
            'Да восторжествует справедливость', 'Да придёт час расплаты за грехи', 'Указа об обвинении',
            'Свирепых кулаков стужи',
        ],
        skills={
            'attack': ['обычной атаки Свирепых кулаков стужи', 'Свирепых кулаков стужи', 'Свирепыми кулаками стужи'],
            'skill': ['Стремительного ледяного клыка'],
            'burst': ['Укуса чернозлатого волка'],
        },
    ),
    default_eng=Template(
        names=[
            'Wriothesley', 'Gracious Rebuke: Unveiling',
            'Gracious Rebuke', 'Rebuke: Vaulting Fist', 'Luster: Vaulting Fist',
            'Chilling Penalty', 'Prosecution Edict', 'There Shall Be an Unveiling for Injustice',
            'There Shall Be a Plea for Justice', 'Repelling Fists',
            'There Shall Be a Reckoning for Sin',
        ],
        skills={
            'attack': ['Normal Attack: Forceful Fists of Frost'],
            'skill': ['Icefang Rush'],
            'burst': ['Darkgold Wolfbite'],
        },
    ),
    there_shall_be_an_unveiling_for_injustice_rus=Template(
        replace={
            'Кроме того, находясь ': 'Находясь ',
            'Кроме того, третий ': 'Третий ',
        },
        sentences=[
            [],
            [],
            ['60:ignore'],
            ['30:ignore'],
            ['2:ignore'],
            [],
            ['60:', '80:', '100:'],
            [],
            ['30:dmg_reaction_stellar_conduct'],
            [],
            [],
        ],
        results=[
            ['skill{Сияние - Звёздный проводник}:', 2, 3, 4],
            [10],
            ['skill{Сияние - Звёздный проводник}:', 5, 6, 7, 8],
        ],
    ),
    there_shall_be_an_unveiling_for_injustice_eng=Template(
        replace={
            'Additionally, when ': 'When ',
            'Additionally, the ': 'The ',
        },
        sentences=[
            [],
            [],
            ['60:ignore', '30:ignore'],
            ['2:ignore'],
            [],
            ['60:', '80:', '100:'],
            ['30:dmg_reaction_stellar_conduct'],
            [],
            [],
        ],
        results=[
            ['skill{Radiance: Stellar-Conduct}:', 2, 3],
            [8],
            ['skill{Radiance: Stellar-Conduct}:', 4, 5, 6],
        ],
    ),
    icefang_rush_rus=Template(
        replace={
            '·': '·\n',
        },
        sentences=[
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            ['50:ignore'],
            ['0.1:ignore'],
            [],
            [],
            [],
            [],
            [],
            [],
        ],
        results=[
            list(range(0, 16)),
            [8],
            [2],
        ],
        extracted_names=[2],
    ),
    icefang_rush_eng=Template(
        replace={
            '·': '·\n',
        },
        sentences=[
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            ['50:ignore'],
            [],
            ['0.1:ignore'],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
        ],
        results=[
            list(range(0, 18)),
            [8, 9],
            [2],
        ],
        extracted_names=[2],
    ),
    there_shall_be_a_plea_for_justice_rus=Template(
        sentences=[
            ['60:ignore'],
            [],
            ['50:dmg_charged_wriothesley', '30:ignore'],
            [],
            ['1:ignore', '5:ignore'],
        ],
    ),
    there_shall_be_a_plea_for_justice_eng=Template(
        sentences=[
            ['60:ignore'],
            [],
            ['50:dmg_charged_wriothesley', '30:ignore'],
            [],
            ['5:ignore'],
        ],
    ),
    there_shall_be_a_reckoning_for_sin=Template(
        sentences=[
            [],
            ['5:ignore'],
            ['6:atk_percent'],
        ],
    ),
    terror_for_the_evildoers_rus=Template(
        sentences=[
            [],
            [],
            ['60:ignore'],
            ['1:ignore', '2.5:ignore'],
            [],
            [],
            [],
            ['200:'],
            [],
            ['4:ignore'],
            [],
            [],
            [],
        ],
    ),
    terror_for_the_evildoers_eng=Template(
        sentences=[
            [],
            [],
            ['60:ignore', '1:ignore', '2.5:ignore'],
            [],
            [],
            [],
            ['200:'],
            [],
            ['4:ignore', '1:ignore', '1:ignore'],
            [],
            [],
        ],
    ),
    terror_for_the_evildoers_hex_rus=Template(
        sentences=[
            [],
            [],
            ['60:ignore'],
            ['1:ignore', '2.5:ignore'],
            [],
            [],
            [],
            ['200:'],
            [],
            ['4:ignore'],
            [],
            [],
            [],
            ['5:ignore', '50:'],
            [],
            ['5:ignore', '50:'],
            [],
            ['4:ignore'],
            [],
            [],
            [],
            [],
        ],
        results=[
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 18, 19, 20, 21],
            [11, 12, 13, 16, 17, 18, 19, 20, 21],
            [11, 14, 15],
        ],
    ),
    terror_for_the_evildoers_hex_eng=Template(
        sentences=[
            [],
            [],
            ['60:ignore', '1:ignore', '2.5:ignore'],
            [],
            [],
            [],
            ['200:'],
            [],
            ['4:ignore'],
            [],
            [],
            [],
            ['5:ignore', '50:'],
            [],
            ['5:ignore', '50:'],
            [],
            ['4:ignore'],
            [],
            ['1:ignore', '1:ignore'],
            [],
            [],
        ],
        results=[
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 17, 18, 19, 20],
            [10, 11, 12, 15, 16, 17, 18, 19, 20],
            [10, 13, 14],
        ],
    ),
    shackles_for_the_arrogant=Template(
        sentences=[
            ['40:'],
            [],
            [],
        ],
    ),
    shackles_for_the_arrogant_hex=Template(
        sentences=[
            ['40:'],
            [],
            ['5:ignore'],
            [],
            ['3:ignore', '5:ignore', '90:', '120:', '150:'],
            [],
            [],
            ['125:', '130:'],
            [],
            [],
        ],
    ),
    shackles_for_the_arrogant_hex_eng=Template(
        sentences=[
            ['40:'],
            [],
            ['5:ignore'],
            [],
            ['90:', '120:', '150:'],
            [],
            [],
            ['125:', '130:'],
            [],
            [],
        ],
    ),
    redemption_for_the_suffering_rus=Template(
        replace = {
            'Кроме того, когда ': 'Когда ',
        },
        sentences=[
            ['50:ignore'],
            [],
            [],
            [],
            ['20:', '4:ignore'],
            ['10:', '6:ignore'],
            [],
        ],
        results=[
            [0, 1, 2],
            [3, 4, 5, 6],
        ],
        extracted_names=[
            '$$$name$$$ (вне поля)',
        ],
    ),
    redemption_for_the_suffering_eng=Template(
        replace = {
            'Additionally, when ': 'When ',
        },
        sentences=[
            ['50:ignore'],
            [],
            [],
            [],
            ['20:', '4:ignore'],
            ['10:', '6:ignore'],
            [],
        ],
        results=[
            [0, 1, 2],
            [3, 4, 5, 6],
        ],
        extracted_names=[
            '$$$name$$$ (Off-field)',
        ],
    ),
    redemption_for_the_suffering_hex=Template(
        replace = {
            'Кроме того, когда ': 'Когда ',
            'Additionally, when ': 'When ',
        },
        sentences=[
            ['50:ignore'],
            [],
            [],
            [],
            ['20:', '4:ignore'],
            ['10:', '6:ignore'],
            [],
            [],
            [],
            [],
            ['25:', '20:'],
            ['10:']
        ],
        results=[
            [8, 9, 10, 11],
            [3, 5, 9, 8, 9, 11]
        ],
    ),
    esteem_for_the_innocent=Template(
        sentences=[
            ['10:crit_rate_charged_wriothesley', '80:crit_dmg_charged_wriothesley'],
            ['100:ignore'],
            [],
            [],
            [],
        ],
    ),
    esteem_for_the_innocent_hex=Template(
        sentences=[
            ['10:crit_rate_charged_wriothesley', '80:crit_dmg_charged_wriothesley'],
            ['100:ignore'],
            [],
            [],
            [],
            [],
            ['10:crit_rate_enhancement_wriothesley', '80:crit_dmg_enhancement_wriothesley'],
            ['20:ignore'],
            [],
            [],
            [],
        ],
        results=[
            [4, 5, 6, 7, 8, 9, 10],
        ],
    ),
)
